Repository kool-dev/kool, pull requests merged in 2022-12, with the labels that each got.

#449 Laravel Octane RoadRunner option + Wizard prompt reuse feature
  commands/create.go
  commands/preset.go
  core/automate/actions.go
  core/automate/executor.go
  core/presets/fake_parser.go
  core/presets/fake_parser_test.go
  core/presets/parser.go
  docs/1-Getting-Started/2-Installation.md
  docs/2-Presets/Laravel+Octane.md
  presets/laravel+octane/config.yml
  recipes/php-8.1-roadrunner.yml
  recipes/php-8.1-swoole.yml
  templates/app/php81-roadrunner.yml
  templates/scripts/laravel+octane+roadrunner.yml
  templates/scripts/laravel+octane+swoole.yml
Labels: release-drafter:added, release-drafter:changed, release-drafter:minor

#450 Kool cloud - new subcommand + documentation
  commands/cloud.go
  commands/create.go
  commands/deploy.go
  commands/root.go
  commands/root_test.go
  docs/3-Deploy-to-Kool-Cloud/1-Getting-Started.md
  docs/3-Deploy-to-Kool-Cloud/2-kool.deploy.yml-Reference.md
  docs/4-Commands/0-kool.md
  docs/4-Commands/kool-cloud.md
Labels: release-drafter:added, release-drafter:changed, release-drafter:major, release-drafter:minor

#453 Improve error message on docker compose check failure
  services/checker/checker.go
  services/checker/checker_test.go
Labels: release-drafter:fixed, release-drafter:patch

#452 Adding new `kool deploy setup` command + config validator + create interactive
  commands/cloud.go
  commands/cloud_deploy.go
  commands/cloud_deploy_destroy.go
  commands/cloud_deploy_destroy_test.go
  commands/cloud_deploy_exec.go
  commands/cloud_deploy_exec_test.go
  commands/cloud_deploy_logs.go
  commands/cloud_deploy_logs_test.go
  commands/cloud_deploy_test.go
  commands/cloud_setup.go
  commands/create.go
  core/shell/prompt_input.go
  go.mod
  go.sum
  presets/golang-cli/config.yml
  services/checker/checker.go
  services/checker/checker_test.go
  services/cloud/deploy_validator.go
  services/compose/consolidated_compose.go
  templates/kool.deploy.yml
Labels: release-drafter:added, release-drafter:changed, release-drafter:minor
