Repository kool-dev/kool, pull requests merged in 2023-09, with the labels that each got.

#470 Fixing PhpUnit Default Folder
  templates/scripts/laravel+octane+roadrunner.yml
  templates/scripts/laravel+octane+swoole.yml
  templates/scripts/laravel.yml
Labels: release-drafter:fixed, release-drafter:patch

#465 kool cloud deploy flags
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  commands/cloud_deploy.go
  commands/cloud_deploy_test.go
  services/cloud/api/deploy.go
Labels: release-drafter:added

#471 Upgrade go 1.21
  .devcontainer/devcontainer.json
  .github/workflows/golangci-lint.yml
  .github/workflows/test.yml
  Dockerfile
  build_artifacts.sh
  go.mod
  go.sum
  kool.yml
Labels: release-drafter:changed, release-drafter:minor
